<a href="https://colab.research.google.com/github/Weedmastercrucifer/CNN-with-Qlearning/blob/main/IIC_Qlearningmodel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install gym
import numpy as np
import gym

In [ ]:
#Building the environment
env = gym.make('FrozenLake-v0')

In [ ]:
epsilon = 0.9
total_episodes = 500
max_steps = 100
alpha = 0.1
#gamma = 0.95
 
#Initializing the Q-matrix
Q = np.zeros((env.observation_space.n, env.action_space.n))

SyntaxError: ignored

In [ ]:
#Function to choose the next action
def choose_action(state):
    action=0
    if np.random.uniform(0, 1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q[state, :])
    return action
 
#Function to learn the Q-value
def update(state, state2, reward, action, action2):
    predict = Q[state, action]
    #target = reward + gamma * Q[state2, action2]
    Q[state, action] = Q[state, action] + alpha * (reward+ Q[state2,action2] - predict)

In [ ]:
#Initializing the reward
reward=0

# Starting the Q learning
for episode in range(total_episodes):
	t = 0
	state1 = env.reset()
	action1 = choose_action(state1)

	while t < max_steps:
		#Visualizing the training
		env.render()
		
		#Getting the next state
		state2, reward, done, info = env.step(action1)

		#Choosing the next action
		action2 = choose_action(state2)
		
		#Learning the Q-value
		update(state1, state2, reward, action1, action2)

		state1 = state2
		action1 = action2
		
		#Updating the respective vaLues
		t += 1
		reward += 1
		
		#If at the end of learning process
		if done:
			break

Streaming output truncated to the last 5000 lines.

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG

SFFF
FHFH
FFFH
HFFG
 

In [ ]:
#Evaluating the performance
print ("Performance : ", reward/total_episodes)
 
#Visualizing the Q-matrix
print(Q)

Performance :  0.002
[[3.18803660e-05 3.51213099e-05 4.50931572e-05 5.56430568e-05]
 [2.33617194e-05 4.67573257e-05 9.56127419e-05 6.75506737e-05]
 [2.89759216e-04 2.44152997e-05 3.15291203e-04 9.65959478e-05]
 [5.61942701e-07 4.03204450e-05 2.35510827e-07 8.87858634e-06]
 [1.90158256e-05 3.59338532e-05 4.37272330e-05 1.91433591e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.12507607e-03 0.00000000e+00 8.54982596e-05 3.89648544e-12]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.00423512e-05 3.87851424e-04 1.41549851e-05 2.86371317e-04]
 [5.63310717e-05 1.51380224e-04 3.32916503e-03 4.72588223e-03]
 [1.40866846e-02 2.48011100e-04 2.00507334e-02 5.60038752e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.04592926e-04 2.69947300e-02 4.34281737e-02 6.68727385e-04]
 [1.37362885e-02 2.70782154e-01 1.01983040e-01 1.95371565e-01]
 [0.00000000e+00 0.00000000e+00 0.